apiVersion: db2u.databases.ibm.com/v1
kind: DvService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.cpd_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave | default "-3" | quote }} 
spec:
  license:
    accept: true
    license: Enterprise
  version: {{ .Values.spec.version }}
  size: {{ .Values.spec.size }}                    