# Default values for ibm-ace-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: dv-service
cpd_namespace: gitops-cp4d-instance
spec:
  license:
    accept: true
    license: Enterprise
  version: 1.7.5
  size: small